name: flutter_chess
description: Full chess app with AI, animations, custom pieces, multiplayer & sounds
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Chess logic
  chess: ^0.8.1

  # Firebase â€“ use latest major compatible with your Flutter 3.38
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Audio
  audioplayers: ^6.5.1

  # For animations & gestures
  flutter_svg: ^2.1.0
  provider: ^6.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pieces/white/
    - assets/pieces/black/
    - assets/sounds/
